### ISSUE TITLE
nim-registry is not GC safe so cannot be used in spawn

### ISSUE THREAD

**Issue by genotrance** [miere43/nim-registry#4]
I'm trying to run a proc in parallel using spawn but it doesn't compile since winregistry is using a global variable:-

> winregistry.nim(356, 6) Warning: 'queryMaxKeyLength' is not GC-safe as it accesses 'nullWinString' which is a global using GC'ed memory [GcUnsafe2]

This can be fixed by letting each proc have its own copy of nullWinString. There seem to be multiple instances of this:-

> queryMaxKeyLength()
> countValues()
> countSubkeys()

**Comment by miere43** [comment]
Works now?

**Comment by genotrance** [comment]
Yep works great, thanks!
