### ISSUE TITLE
2147483648 can't be converted to RegHandle?

### ISSUE THREAD

**Issue by ghost** [miere43/nim-registry#7]
when i compile, there raises an error:

```
C:\Users\Administrator\.nimble\pkgs\winregistry-0.2.0\winregistry.nim(73, 45) Error: 2147483648 can't be converted to RegHandle
```

`2147483648` means `HKEY_CLASSES_ROOT`, but I only use `HKEY_CURRENT_USER`

so, it seems like there are some errors in type `RegHandle`?

**Comment by azlan** [comment]
You are getting this error when compiling for 32 bit arch. The workaround is to use `uint` instead of `HANDLE`: 
https://github.com/miere43/nim-registry/blob/devel/winregistry.nim#L7

Araq is using `uint` here, https://github.com/nim-lang/Nim/blob/devel/lib/windows/registry.nim#L15

**Comment by miere43** [comment]
Fixed in https://github.com/miere43/nim-registry/pull/8.
